### ISSUE TITLE
目录层次太多时会删除失败

### ISSUE THREAD

**Issue by yunnysunny** [hezedu/fuckwinfsdel#1]
```
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC'
16917/16917
结束, 共有5635个文件删除失败,请关闭其它可能占用该文件夹的程序再试.
最深达 3223 层.用时:84740ms
```

**Comment by hezedu** [comment]
你用的window的话，提示上说的很明白：`请关闭其它可能占用该文件夹的程序再试` , <br/>你重启电脑再试试。

另外3千多层的目录？

**Comment by yunnysunny** [comment]
是的 这个目录是误操作产生的 应该不是被占用了 用window自带的删除功能的时候没有报错 只是操作完成后文件还在 我再试试

**Comment by hezedu** [comment]
3千多层也是可以删的，只是会很慢。

**Comment by yunnysunny** [comment]
我现在重新操作了一遍，运行` fuckwinfsdel build`还是失败：
```
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build'
rmdir Error ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build'
9657/9657
结束, 共有3217个文件删除失败,请关闭其它可能占用该文件夹的程序再试.
最深达 3218 层.用时:70911ms
```
我的文件结构是无数个build文件夹递归循环，而且我可以保证当前文件夹没有被占用。
我重复运行一遍提示信息变成：
```
9651/9651
结束, 共有3215个文件删除失败,请关闭其它可能占用该文件夹的程序再试.
最深达 3216 层.用时:69508ms
```
运行第三遍，提示：
```
9645/9645
结束, 共有3213个文件删除失败,请关闭其它可能占用该文件夹的程序再试.
最深达 3214 层.用时:68279ms
```

**Comment by hezedu** [comment]
你找一下第一行出错信息：
![image](https://user-images.githubusercontent.com/8508437/30629243-6e07fb18-9e0d-11e7-9495-bcd04857db80.png)

**Comment by yunnysunny** [comment]
输出的内容太多了，超出了命令行的缓冲区，没法看到更多的输出信息

**Comment by hezedu** [comment]
在出错的时候，`ctrl + c` 停止。

**Comment by yunnysunny** [comment]
太多了，一眼根本扫不过来

**Comment by hezedu** [comment]
用本地API：
```js
var del = require('fuckwinfsdel');
del('./build', {
    onFail: function(method, err){
      console.log('err', err.message.substr(0, 300), 'length', err.message.length)
      throw err
    }
});
```

**Comment by hezedu** [comment]
改了一下，这样可以看到第一个错误了：
```js
var del = require('fuckwinfsdel');
del('./build', {
    onFail: function(method, err){
      console.log('info:', err.message.substr(0, 100));
      console.log('length', err.message.length);
      process.exit();
    }
});
```

**Comment by yunnysunny** [comment]
```javascript
var del = require('fuckwinfsdel');
del('./build', {
    onFail: function(method, err){
      console.log('info:', err.message.substr(0, 100));
      console.log('length', err.message.length);
      process.exit();
    }
});
```
**del.js**
```
{lamb} node del.js
D:\program2\npm\fuckwinfsdel:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\temp\node\openCC\openCC\files\del.js:1:73)
    at Module._compile (module.js:570:32)
```
**输出**

**Comment by hezedu** [comment]
你命令行工具有问题。用window的cmd

**Comment by yunnysunny** [comment]
windows自带的也有问题：
```
D:\temp\node\openCC\openCC\files>node del.js
d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\fuckwinfsdel:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\temp\node\openCC\openCC\files\del.js:1:73)
    at Module._compile (module.js:570:32)
```

**Comment by hezedu** [comment]
你安装了吗？ `npm install fuckwinfsdel`

**Comment by yunnysunny** [comment]
装完之后可以运行了，报错：
```
D:\temp\node\openCC\openCC\files>node del.js
info: ENOTEMPTY: directory not empty, rmdir 'D:\temp\node\openCC\openCC\files\build\build\build\build\buil
length 19326
```

**Comment by hezedu** [comment]
这应该是当你删的时候有程序在该目录创建文件， 所以会报这个错。这也是window自身的BUG。详见： https://github.com/isaacs/rimraf/issues/25 

你关掉某些反病毒程序再试试。

**Comment by yunnysunny** [comment]
没有用，禁用windows defender也没有用

**Comment by hezedu** [comment]
不过看执行的情况是能删掉几个文件夹的。你可以这样：

在同目录下创建两文件:

**del.js**
```js
var del = require('fuckwinfsdel');
del('./build', {
    onFail: function(method, err){
      var msg = '$ERROR$' + err.message.length + '$ERROR$'
      throw msg
    }
});
```
**loop.js**
```js
const exec = require('child_process').exec;
function loop(num){
  exec('node del.js', function(err){
    if(err){
      if(num !== 0){

        let msg = err.message;
        let fI = msg.indexOf('$ERROR$') + 7;
        msg = msg.substr(fI, msg.lastIndexOf('$ERROR$') - fI);

        console.log('step: ', num, 'length:', msg);
          loop(num - 1);
      }
    }
  })
}

loop(3100);
```
执行loop。直到删完为止。

**Comment by yunnysunny** [comment]
创建这么多进程，操作系统还能正常运行吗



yunnysunny
 
发件人： Du Wei
发送时间： 2017-09-21 14:47
收件人： hezedu/fuckwinfsdel
抄送： 白一梓; Author
主题： Re: [hezedu/fuckwinfsdel] 目录层次太多时会删除失败 (#1)
不过看执行的情况是能删掉几个文件夹的。你可以这样：
创建两文件:
del.js
var del = require('fuckwinfsdel');
del('./build', {
    onFail: function(method, err){
      var msg = '$ERROR$' + err.message.length + '$ERROR$'
      throw msg
    }
});
loop.js
const exec = require('child_process').exec;
function loop(num){
  exec('node del.js', function(err){
    if(err){
      if(num !== 0){
        let msg = err.message;
        let fI = msg.indexOf('$ERROR$') + 7;
        msg = msg.substr(fI, msg.lastIndexOf('$ERROR$') - fI);
        console.log('step: ', num, 'length:', msg);
          loop(num - 1);
      }
    }
  })
}
loop(3100);
执行loop。直到删完为止。

**Comment by hezedu** [comment]
一个挂了，另一个继续。只有一个进程呀。
